# Generated by Django 5.0.6 on 2024-12-08 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='цена за тест для клиники')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Генетический тест',
                'verbose_name_plural': '1. Генетические тесты',
            },
        ),
        migrations.CreateModel(
            name='DetectionKitMarkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuc_var_1_clin_signif', models.CharField(blank=True, choices=[('NORM', 'NORM'), ('MUT', 'MUT'), ('NOT ASSIGNED', 'не назначено')], default='не назначено', max_length=24, null=True, verbose_name='интерпретация аллели: MUT или NORM')),
                ('nuc_var_2_clin_signif', models.CharField(blank=True, choices=[('NORM', 'NORM'), ('MUT', 'MUT'), ('NOT ASSIGNED', 'не назначено')], default='не назначено', max_length=24, null=True, verbose_name='интерпретация аллели: MUT или NORM')),
                ('marker_category_in_kit', models.CharField(blank=True, choices=[('Механические свойства', 'Механические свойства'), ('Увлажнение', 'Увлажнение'), ('Фотозащита', 'Фотозащита'), ('Воспаление', 'Воспаление'), ('Пищевые непереносимости', 'Пищевые непереносимости'), ('Гормоны', 'Гормоны')], max_length=255, null=True)),
                ('detection_kit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection_kits.detectionkit')),
                ('marker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='markers.singlenucpol')),
            ],
            options={
                'verbose_name': 'Маркеры в генетическом тесте',
                'verbose_name_plural': 'Маркеры в генетических тестах',
            },
        ),
        migrations.AddField(
            model_name='detectionkit',
            name='linked_markers',
            field=models.ManyToManyField(related_name='detection_kits_list', through='detection_kits.DetectionKitMarkers', to='markers.singlenucpol'),
        ),
        migrations.AddConstraint(
            model_name='detectionkitmarkers',
            constraint=models.UniqueConstraint(fields=('detection_kit', 'marker'), name='detection_kit_marker_constraint'),
        ),
    ]
