# Generated by Django 5.0.6 on 2024-12-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionkitmarkers',
            options={'verbose_name': 'Добавить маркер', 'verbose_name_plural': 'Маркеры, интерпретация, заключения'},
        ),
        migrations.AlterField(
            model_name='detectionkitmarkers',
            name='nuc_var_1_clin_signif',
            field=models.CharField(blank=True, choices=[('NORM', 'NORM'), ('MUT', 'MUT'), ('NOT ASSIGNED', 'не назначено')], default='не назначено', help_text="aллель 1 находится ДО знака '/' в описании маркера слева, например: G/A: аллель 1 - G", max_length=24, null=True, verbose_name='интерпретация аллели 1'),
        ),
        migrations.AlterField(
            model_name='detectionkitmarkers',
            name='nuc_var_2_clin_signif',
            field=models.CharField(blank=True, choices=[('NORM', 'NORM'), ('MUT', 'MUT'), ('NOT ASSIGNED', 'не назначено')], default='не назначено', help_text="aллель 2 находится ПОСЛЕ знака '/' в описании маркера слева, например: G/A: аллель 2 - А", max_length=24, null=True, verbose_name='интерпретация аллели 2'),
        ),
    ]
