# Generated by Django 5.0.6 on 2024-12-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0002_alter_detectionkitmarkers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionkitmarkers',
            name='conclusion_genotype_1_1',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='заключение для генотипа 1'),
        ),
        migrations.AddField(
            model_name='detectionkitmarkers',
            name='conclusion_genotype_1_2',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='заключение для генотипа 2'),
        ),
        migrations.AddField(
            model_name='detectionkitmarkers',
            name='conclusion_genotype_2_2',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='заключение для генотипа 3'),
        ),
    ]
