# Generated by Django 5.0.6 on 2024-12-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0003_detectionkitmarkers_conclusion_genotype_1_1_and_more'),
        ('markers', '0003_alter_singlenucpol_gene_name_full_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionkitmarkers',
            options={'verbose_name': 'SNP', 'verbose_name_plural': '2. SNP в тестах. заключения по генотипам'},
        ),
        migrations.CreateModel(
            name='TwoSNPCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('note', models.TextField(max_length=1000)),
                ('genetic_test', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_rule', to='detection_kits.detectionkit')),
                ('snp_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_rules_snp_1', to='markers.singlenucpol')),
                ('snp_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_rules_snp_2', to='markers.singlenucpol')),
            ],
            options={
                'verbose_name': 'Комбинация двух SNP',
            },
        ),
        migrations.CreateModel(
            name='TwoSNPCombinationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genotype_snp_1', models.CharField(blank=True, max_length=2, null=True)),
                ('genotype_snp_2', models.CharField(blank=True, max_length=2, null=True)),
                ('report', models.TextField(blank=True, max_length=10000, null=True)),
                ('report_rule_two_snp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection_kits.twosnpcombination')),
            ],
            options={
                'verbose_name': 'заключение по двум генотипам',
                'verbose_name_plural': 'заключения по двум генотипам',
            },
        ),
    ]
