# Generated by Django 5.0.6 on 2024-12-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0004_alter_detectionkitmarkers_options_twosnpcombination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twosnpcombination',
            options={'verbose_name': '3. Комбинация двух SNP'},
        ),
        migrations.RemoveField(
            model_name='detectionkit',
            name='price',
        ),
    ]
