# Generated by Django 5.0.6 on 2024-12-21 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_kits', '0005_alter_twosnpcombination_options_and_more'),
        ('markers', '0003_alter_singlenucpol_gene_name_full_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionkitmarkers',
            options={'verbose_name': 'SNP', 'verbose_name_plural': '2. SNP в тестах и заключения по отдельным генотипам'},
        ),
        migrations.AlterField(
            model_name='detectionkitmarkers',
            name='detection_kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detection_kits.detectionkit'),
        ),
        migrations.AlterField(
            model_name='detectionkitmarkers',
            name='marker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='markers.singlenucpol'),
        ),
    ]
