# Generated by Django 5.0.6 on 2024-12-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlenucpol',
            name='genotype_nuc_var_1_1',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='генотип: аллель 1 + аллель 1'),
        ),
        migrations.AddField(
            model_name='singlenucpol',
            name='genotype_nuc_var_1_2',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='генотип: аллель 1 + аллель 2'),
        ),
        migrations.AddField(
            model_name='singlenucpol',
            name='genotype_nuc_var_2_2',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='генотип: аллель 1 + аллель 2'),
        ),
    ]
