# Generated by Django 5.0.6 on 2024-12-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_singlenucpol_genotype_nuc_var_1_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlenucpol',
            name='gene_name_full',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ген'),
        ),
        migrations.AlterField(
            model_name='singlenucpol',
            name='gene_name_short',
            field=models.CharField(max_length=20, verbose_name='ген, краткое обозначение'),
        ),
        migrations.AlterField(
            model_name='singlenucpol',
            name='genotype_nuc_var_1_1',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='генотип 1: аллель 1 + 1'),
        ),
        migrations.AlterField(
            model_name='singlenucpol',
            name='genotype_nuc_var_1_2',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='генотип 2: аллель 1 + 2'),
        ),
        migrations.AlterField(
            model_name='singlenucpol',
            name='genotype_nuc_var_2_2',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='генотип 3: аллель 2 + 2'),
        ),
        migrations.AlterField(
            model_name='singlenucpol',
            name='nuc_var_1',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('G', 'G'), ('T', 'T'), ('5A', '5A'), ('6A', '6A'), ('_', '_')], max_length=2, verbose_name='аллель 1'),
        ),
        migrations.AlterField(
            model_name='singlenucpol',
            name='nuc_var_2',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('G', 'G'), ('T', 'T'), ('5A', '5A'), ('6A', '6A'), ('_', '_')], max_length=2, verbose_name='аллель 2'),
        ),
    ]
