# Generated by Django 5.0.6 on 2024-12-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_alter_resultsnp_options_alter_sample_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='full_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sample',
            name='short_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
